services:
  agente-sgsst:
  # Omit build if you want to pull or build directly
    build: .
    container_name: agente_sgsst_container
    restart: unless-stopped
    volumes:
      - ./sistema_gestion:/app/sistema_gestion
      - ./data:/app/data
      - ./.env:/app/.env:ro
      - ./credentials.json:/app/credentials.json
      - ./token.pickle:/app/token.pickle
    stdin_open: true
    tty: true
