[project]
name = "agente-sgsst"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Julian Correa", email = "juliancorrea1630@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "google-api-python-client>=2.200.0",
    "google-auth-oauthlib>=1.4.1",
    "google-generativeai>=0.8.6",
    "openai>=3.8.0",
    "python-docx>=1.2.0",
    "requests>=2.34.2",
]

[project.scripts]
agente-sgsst = "agente_sgsst.main:main"

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "agente_sgsst"
module-root = "src"

[tool.pytest.ini_options]
pythonpath = [".", "src"]

